# NumPy Essesentials

In [1]:
import numpy as np

In [2]:
## NumPy arrays come in two flavours 1) Vectors (One Dimensional) and 2) Metrices (Two Dimensional)

In [3]:
## Define a vector
## using list

vector_1 = np.array([1,2,3,4,5,6])

In [4]:
type(vector_1)

numpy.ndarray

In [5]:
vector_1

array([1, 2, 3, 4, 5, 6])

In [6]:
## using range function

vector_2 = np.array(range(11))

In [7]:
vector_2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
type(vector_2)

numpy.ndarray

In [9]:
## using tuples

vector_3 = np.array((1,2,3,4,5,6))

In [10]:
type(vector_3)

numpy.ndarray

In [11]:
vector_3

array([1, 2, 3, 4, 5, 6])

In [12]:
## Define a matrix

elements = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]

matrix_1 = np.array(elements)

In [13]:
type(matrix_1)

numpy.ndarray

In [14]:
matrix_1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [15]:
## using tuples

elements = ((1,2,3),(4,5,6),(7,8,9))

matrix_2 = np.array(elements)

In [16]:
type(matrix_2)

numpy.ndarray

In [17]:
matrix_2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Array creation using different numpy methods

### arange()

In [18]:
array_1 = np.arange(0,11,1)

In [19]:
type(array_1)

numpy.ndarray

In [20]:
array_2 = np.arange(0,10,0.5)

In [21]:
array_2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [22]:
len(array_2)

20

### linspace()

In [23]:
array_3 = np.linspace(0,100,100)

In [24]:
array_3

array([  0.        ,   1.01010101,   2.02020202,   3.03030303,
         4.04040404,   5.05050505,   6.06060606,   7.07070707,
         8.08080808,   9.09090909,  10.1010101 ,  11.11111111,
        12.12121212,  13.13131313,  14.14141414,  15.15151515,
        16.16161616,  17.17171717,  18.18181818,  19.19191919,
        20.2020202 ,  21.21212121,  22.22222222,  23.23232323,
        24.24242424,  25.25252525,  26.26262626,  27.27272727,
        28.28282828,  29.29292929,  30.3030303 ,  31.31313131,
        32.32323232,  33.33333333,  34.34343434,  35.35353535,
        36.36363636,  37.37373737,  38.38383838,  39.39393939,
        40.4040404 ,  41.41414141,  42.42424242,  43.43434343,
        44.44444444,  45.45454545,  46.46464646,  47.47474747,
        48.48484848,  49.49494949,  50.50505051,  51.51515152,
        52.52525253,  53.53535354,  54.54545455,  55.55555556,
        56.56565657,  57.57575758,  58.58585859,  59.5959596 ,
        60.60606061,  61.61616162,  62.62626263,  63.63

### zeros()

In [25]:
array_4 = np.zeros(4)

In [26]:
array_4

array([0., 0., 0., 0.])

In [27]:
array_5 = np.zeros((4,4))

In [28]:
array_5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### ones()

In [29]:
array_5 = np.ones(4)

In [30]:
array_5 = np.ones((4,4))

In [31]:
array_5

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### eye()

In [32]:
array_6 = np.eye(4)

In [33]:
array_6

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [34]:
array_7 = np.eye(1)

In [35]:
array_7

array([[1.]])

## Random 

### rand()

In [36]:
array_8 = np.random.rand(3,2)

In [37]:
array_8

array([[0.83999008, 0.38300654],
       [0.54681959, 0.5797996 ],
       [0.16960336, 0.43203328]])

In [38]:
array_9 = np.random.rand(3,3)

In [39]:
array_9

array([[0.67593188, 0.19458626, 0.42221413],
       [0.1608699 , 0.34531763, 0.0441175 ],
       [0.03182342, 0.35577842, 0.71351023]])

In [40]:
array_9 = np.random.rand(4)

In [41]:
array_9

array([0.51879226, 0.94245314, 0.55076701, 0.63892371])

### randn()

In [42]:
array_10 = np.random.randn(5)

In [43]:
array_10

array([-1.45341325,  0.30011672,  0.78522096,  0.40607313,  0.03082906])

In [44]:
array_10 = np.random.randn(5,5)

In [45]:
array_10

array([[-0.36876736,  0.49132223, -1.28480512,  0.29399856,  0.65616449],
       [-1.13251307, -1.027333  , -0.27225371,  0.38475562,  0.91557422],
       [-0.65865073, -0.55490687, -0.33528868, -0.52174665, -0.0494817 ],
       [ 0.77948064, -0.8740393 ,  0.47612698,  0.07164642,  1.79302373],
       [ 1.08544278,  0.85978845, -1.0316953 ,  0.70322049,  0.52829641]])

### randint()

In [46]:
array_11 = np.random.randint(0,100,10)

In [47]:
array_11

array([29, 19, 49, 65, 45, 74, 60, 11, 94, 73])

In [48]:
array_12 = np.random.randint(0,100,(10,10))

In [49]:
array_12

array([[24, 74, 81, 69,  6, 50, 71, 18,  0, 79],
       [91, 51, 86, 39, 50, 79, 20, 41, 23,  2],
       [46, 55, 43, 26, 52, 99,  4, 13, 57, 92],
       [ 9, 87, 27, 93,  9, 77, 21, 48, 70, 77],
       [ 4, 72, 93, 61, 65,  6, 35, 51,  7, 82],
       [37, 38, 12, 78, 41, 11, 53, 77, 31, 94],
       [70, 78, 85, 71, 65, 38, 68, 23,  6, 65],
       [90, 40, 13, 11, 51, 73, 81, 47, 12, 21],
       [22,  8, 76,  9, 48, 51, 81, 18, 33, 65],
       [94,  2, 95, 44, 82, 69, 89,  6, 86, 65]])

## Array Methods and Attributes

In [50]:
## reshape()

array_13 = np.arange(9)

In [51]:
array_13

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [52]:
array_13.reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [53]:
array_14 = np.random.randint(0,1000,(10,10))

In [54]:
array_14

array([[625,  46, 797, 359,  68, 611, 545, 508, 526, 506],
       [893,  62, 827, 568, 329, 138, 842, 526,  24, 736],
       [418, 663, 300, 120, 316,  74,  75, 592, 740, 423],
       [906, 925, 341, 799, 807, 385, 211,  92, 592,  42],
       [373, 118, 435, 147, 373, 953, 478, 264, 433, 394],
       [237, 512, 515, 568, 683, 824, 497, 138, 239, 580],
       [939, 349, 974, 362, 199, 156, 103, 106, 831,  72],
       [738, 902, 566, 922, 215, 354, 287, 322, 354, 458],
       [657, 368, 646, 864, 297, 914,  29, 803, 170,   3],
       [222, 153, 230, 426, 300,  30, 653, 818, 449, 556]])

In [55]:
## min(), max(), argmin(), argmax()

array_14.min()

3

In [56]:
array_14.max()

974

In [57]:
array_14.argmin()

89

In [58]:
array_14.argmax()

62

## Attributes

In [59]:
## size(), shape() and dtype()

array_15 = np.linspace(0,10,50)

In [60]:
array_15

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [61]:
array_15.shape

(50,)

In [62]:
array_16 = array_15.reshape(5,10)

In [63]:
array_16.shape

(5, 10)

In [64]:
array_16, array_15

(array([[ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
          1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469],
        [ 2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
          3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102],
        [ 4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
          5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735],
        [ 6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
          7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367],
        [ 8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
          9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ]]),
 array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
         1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
         2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
         3.06122449,  3.26530612, 

In [65]:
array_15.size

50

In [66]:
array_15.dtype

dtype('float64')

In [67]:
array_1 = np.random.randint(0,100,20)

In [68]:
array_1

array([ 9, 25, 51, 95, 42, 66, 18, 31, 62, 32,  6, 37,  5, 30, 13, 25, 34,
       26, 18, 44])

## Indexing and Slicing of Arrays

In [69]:
array_1[0]

9

In [70]:
array_1[-1]

44

In [71]:
array_1[:5]

array([ 9, 25, 51, 95, 42])

In [72]:
array_1[2:7]

array([51, 95, 42, 66, 18])

In [73]:
array_1[-3:]

array([26, 18, 44])

In [74]:
array_1[1:-11]

array([25, 51, 95, 42, 66, 18, 31, 62])

In [75]:
array_1[5:]

array([66, 18, 31, 62, 32,  6, 37,  5, 30, 13, 25, 34, 26, 18, 44])

## Indexing and Slicing 2D arrays (Matrices)

In [76]:
array2d = np.random.randint(0,100,(5,5))

In [77]:
array2d

array([[77,  2, 62, 69, 32],
       [65, 11, 72, 94, 90],
       [82, 35, 80, 32, 56],
       [66, 48, 81, 44, 95],
       [71, 34, 75, 66, 63]])

## How to access Metrices (SUPER IMPORTANT)

In [78]:
'''
To access any element, the general format is:

array_2d[row][col]
or
array_2d[row,col].

'''

array2d[3,3]

44

In [79]:
array2d[1:3,2:4]

array([[72, 94],
       [80, 32]])

In [80]:
array2d[2]

array([82, 35, 80, 32, 56])

In [81]:
array2d[-1]

array([71, 34, 75, 66, 63])

## Broadcasting

In [85]:
array1 = np.arange(10)

In [86]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
array1[1:7] = 500

In [88]:
array1

array([  0, 500, 500, 500, 500, 500, 500,   7,   8,   9])

In [93]:
array2 = np.ones((4,4))

In [94]:
array2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [97]:
array3 = np.random.randint(0,10,4)
array3

array([1, 7, 6, 9])

In [98]:
array2 + array3

array([[ 2.,  8.,  7., 10.],
       [ 2.,  8.,  7., 10.],
       [ 2.,  8.,  7., 10.],
       [ 2.,  8.,  7., 10.]])

In [99]:
array2 + 200

array([[201., 201., 201., 201.],
       [201., 201., 201., 201.],
       [201., 201., 201., 201.],
       [201., 201., 201., 201.]])

In [106]:
array_1 = np.arange(1,4)
array_2 = np.arange(1,4).reshape(3,1)

In [107]:
array_1, array_2 

(array([1, 2, 3]),
 array([[1],
        [2],
        [3]]))

In [108]:
array_1 + array_2

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

## Fancy Indexing

In [109]:
array = np.random.randint(1,100,(10,10))

In [110]:
array

array([[67, 67, 22, 41, 33, 96, 85, 40, 51, 34],
       [ 9,  6, 99, 84, 81, 30, 16, 44,  4, 77],
       [73, 13, 28, 28, 94, 83, 89, 13, 80, 69],
       [83, 33, 74, 28, 47,  5, 88, 36, 54, 85],
       [39, 28, 90, 14, 88, 79, 53,  2, 69, 30],
       [41, 11, 28, 29, 40, 93, 68, 56, 92, 17],
       [15, 52, 20,  3, 50, 16, 42, 76, 40, 94],
       [17, 49, 27, 22, 14, 36, 65, 14, 79, 11],
       [ 3, 24,  1, 53, 55, 89, 10, 71, 85, 81],
       [19, 20, 60, 42, 81, 90,  6,  9, 70, 41]])

In [117]:
## Grabbing rows

array[[2,4,6,8]]

array([[73, 13, 28, 28, 94, 83, 89, 13, 80, 69],
       [39, 28, 90, 14, 88, 79, 53,  2, 69, 30],
       [15, 52, 20,  3, 50, 16, 42, 76, 40, 94],
       [ 3, 24,  1, 53, 55, 89, 10, 71, 85, 81]])

In [125]:
## Grabbing columns

array[:,[2,3,5,7]]

array([[22, 41, 96, 40],
       [99, 84, 30, 44],
       [28, 28, 83, 13],
       [74, 28,  5, 36],
       [90, 14, 79,  2],
       [28, 29, 93, 56],
       [20,  3, 16, 76],
       [27, 22, 36, 14],
       [ 1, 53, 89, 71],
       [60, 42, 90,  9]])

## Boolean Mask Arrays

In [128]:
array = np.linspace(0,9,10)
array

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [129]:
array%2==0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [130]:
array[array%2==0]

array([0., 2., 4., 6., 8.])

In [132]:
## Using a metrices

array = np.random.randint(1,100,(10,10))

In [133]:
array

array([[55, 10, 42, 67,  2, 88, 86, 92, 49, 70],
       [43, 15, 47, 52, 92, 14, 76, 62, 76, 99],
       [68, 94, 33, 25, 83, 46,  6, 70, 27, 63],
       [39, 55, 16, 46, 69, 90, 71, 37, 47, 28],
       [73, 44,  1,  4, 13, 72, 54, 67, 61, 70],
       [59, 23, 81, 48, 69, 65, 46, 50, 26, 69],
       [44, 48,  9, 66, 61,  5, 51, 62, 26, 32],
       [ 4,  8, 32, 51, 67, 46, 61, 85,  8, 86],
       [32, 40, 12, 55,  7, 72, 29, 35, 29, 57],
       [89, 74, 84, 56, 83, 61, 28, 47, 95, 93]])

In [134]:
bool_array = array>50

In [135]:
bool_array

array([[ True, False, False,  True, False,  True,  True,  True, False,
         True],
       [False, False, False,  True,  True, False,  True,  True,  True,
         True],
       [ True,  True, False, False,  True, False, False,  True, False,
         True],
       [False,  True, False, False,  True,  True,  True, False, False,
        False],
       [ True, False, False, False, False,  True,  True,  True,  True,
         True],
       [ True, False,  True, False,  True,  True, False, False, False,
         True],
       [False, False, False,  True,  True, False,  True,  True, False,
        False],
       [False, False, False,  True,  True, False,  True,  True, False,
         True],
       [False, False, False,  True, False,  True, False, False, False,
         True],
       [ True,  True,  True,  True,  True,  True, False, False,  True,
         True]])

In [139]:
x = array[bool_array]

In [140]:
x.size

52

In [141]:
x.reshape(13,4)

array([[55, 67, 88, 86],
       [92, 70, 52, 92],
       [76, 62, 76, 99],
       [68, 94, 83, 70],
       [63, 55, 69, 90],
       [71, 73, 72, 54],
       [67, 61, 70, 59],
       [81, 69, 65, 69],
       [66, 61, 51, 62],
       [51, 67, 61, 85],
       [86, 55, 72, 57],
       [89, 74, 84, 56],
       [83, 61, 95, 93]])