# NumPy Essesentials

In [1]:
import numpy as np

In [2]:
## NumPy arrays come in two flavours 1) Vectors (One Dimensional) and 2) Metrices (Two Dimensional)

In [3]:
## Define a vector
## using list

vector_1 = np.array([1,2,3,4,5,6])

In [4]:
type(vector_1)

numpy.ndarray

In [5]:
vector_1

array([1, 2, 3, 4, 5, 6])

In [6]:
## using range function

vector_2 = np.array(range(11))

In [7]:
vector_2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
type(vector_2)

numpy.ndarray

In [9]:
## using tuples

vector_3 = np.array((1,2,3,4,5,6))

In [10]:
type(vector_3)

numpy.ndarray

In [11]:
vector_3

array([1, 2, 3, 4, 5, 6])

In [13]:
## Define a matrix

elements = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]

matrix_1 = np.array(elements)

In [14]:
type(matrix_1)

numpy.ndarray

In [15]:
matrix_1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [16]:
## using tuples

elements = ((1,2,3),(4,5,6),(7,8,9))

matrix_2 = np.array(elements)

In [17]:
type(matrix_2)

numpy.ndarray

In [18]:
matrix_2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Array creation using different numpy methods

### arange()

In [23]:
array_1 = np.arange(0,11,1)

In [25]:
type(array_1)

numpy.ndarray

In [26]:
array_2 = np.arange(0,10,0.5)

In [27]:
array_2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [28]:
len(array_2)

20

### linspace()

In [56]:
array_3 = np.linspace(0,100,100)

In [57]:
array_3

array([  0.        ,   1.01010101,   2.02020202,   3.03030303,
         4.04040404,   5.05050505,   6.06060606,   7.07070707,
         8.08080808,   9.09090909,  10.1010101 ,  11.11111111,
        12.12121212,  13.13131313,  14.14141414,  15.15151515,
        16.16161616,  17.17171717,  18.18181818,  19.19191919,
        20.2020202 ,  21.21212121,  22.22222222,  23.23232323,
        24.24242424,  25.25252525,  26.26262626,  27.27272727,
        28.28282828,  29.29292929,  30.3030303 ,  31.31313131,
        32.32323232,  33.33333333,  34.34343434,  35.35353535,
        36.36363636,  37.37373737,  38.38383838,  39.39393939,
        40.4040404 ,  41.41414141,  42.42424242,  43.43434343,
        44.44444444,  45.45454545,  46.46464646,  47.47474747,
        48.48484848,  49.49494949,  50.50505051,  51.51515152,
        52.52525253,  53.53535354,  54.54545455,  55.55555556,
        56.56565657,  57.57575758,  58.58585859,  59.5959596 ,
        60.60606061,  61.61616162,  62.62626263,  63.63

### zeros()

In [60]:
array_4 = np.zeros(4)

In [61]:
array_4

array([0., 0., 0., 0.])

In [62]:
array_5 = np.zeros((4,4))

In [63]:
array_5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### ones()

In [64]:
array_5 = np.ones(4)

In [65]:
array_5 = np.ones((4,4))

In [66]:
array_5

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### eye()

In [67]:
array_6 = np.eye(4)

In [68]:
array_6

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [69]:
array_7 = np.eye(1)

In [70]:
array_7

array([[1.]])

## Random 

### rand()

In [71]:
array_8 = np.random.rand(3,2)

In [72]:
array_8

array([[0.05013094, 0.54193044],
       [0.60545889, 0.3410321 ],
       [0.03029726, 0.19003144]])

In [73]:
array_9 = np.random.rand(3,3)

In [75]:
array_9

array([[0.44223686, 0.86269342, 0.44477817],
       [0.42366056, 0.42405956, 0.36819241],
       [0.86583469, 0.11071899, 0.25786823]])

In [76]:
array_9 = np.random.rand(4)

In [77]:
array_9

array([0.10712159, 0.0194791 , 0.43554075, 0.69904935])

### randn()

In [78]:
array_10 = np.random.randn(5)

In [79]:
array_10

array([ 0.30962316, -1.02558723,  0.15234205, -0.53213487,  0.62180601])

In [80]:
array_10 = np.random.randn(5,5)

In [81]:
array_10

array([[ 1.75721506, -1.79784327,  0.24225064,  0.48695175,  0.46477042],
       [ 1.27906615, -0.30220332,  0.10017957, -0.63002948, -0.75665863],
       [-1.38824805,  0.40836644, -1.42986616,  1.48326014,  1.29841272],
       [ 0.60663381, -0.04232925,  0.12882685, -0.55884835,  0.65440829],
       [-0.89194452,  0.4001384 ,  1.48758669, -1.8187537 , -1.73452678]])

### randint()

In [82]:
array_11 = np.random.randint(0,100,10)

In [83]:
array_11

array([99, 72, 48, 73, 97, 50, 43,  6, 97, 40])

In [84]:
array_12 = np.random.randint(0,100,(10,10))

In [85]:
array_12

array([[43, 12, 18, 12, 69, 42, 91,  0, 85,  4],
       [22, 73, 35, 53, 30, 26, 85, 48, 14, 75],
       [68, 75, 98, 84, 71,  4, 17, 35, 45, 30],
       [43, 37, 80, 11, 75, 77, 80, 63, 79, 99],
       [25, 25, 57, 32, 30, 85, 15, 88, 36, 20],
       [80,  1, 43, 43, 15, 51, 32, 15, 19, 83],
       [74, 38, 88, 93, 83, 33, 38, 32, 32, 36],
       [38, 35, 60, 26,  2, 17, 78, 78, 44,  4],
       [61, 95, 10, 82, 55, 53, 41, 93, 59, 65],
       [28, 49, 65, 73, 48, 75, 73, 25, 15, 33]])

## Array Methods and Attributes

In [88]:
## reshape()

array_13 = np.arange(9)

In [89]:
array_13

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [90]:
array_13.reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [91]:
array_14 = np.random.randint(0,1000,(10,10))

In [92]:
array_14

array([[108, 565,  63, 452,   7, 609,  16, 367, 450, 346],
       [584, 368, 492, 516, 389, 523, 639, 137,  34, 827],
       [235, 312, 148,   4, 192, 857, 575, 664, 436, 438],
       [935, 794, 674, 559, 806, 852, 922, 774, 484, 292],
       [624, 447,  99, 498, 486, 701, 138, 230, 539, 352],
       [537, 549, 855,  78,  69, 343, 728, 272, 594, 774],
       [354, 194, 731, 921, 982, 240, 962, 694, 795, 566],
       [  4,  65, 282, 687, 729, 970, 244, 807, 289, 229],
       [327,  30, 879, 511, 314, 540, 134, 389, 868,  76],
       [307, 343,  85, 450, 535, 517, 433, 560, 687, 260]])

In [93]:
## min(), max(), argmin(), argmax()

array_14.min()

4

In [94]:
array_14.max()

982

In [96]:
array_14.argmin()

23

In [97]:
array_14.argmax()

64

## Attributes

In [100]:
## size(), shape() and dtype()

array_15 = np.linspace(0,10,50)

In [101]:
array_15

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [102]:
array_15.shape

(50,)

In [103]:
array_16 = array_15.reshape(5,10)

In [104]:
array_16.shape

(5, 10)

In [105]:
array_16, array_15

(array([[ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
          1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469],
        [ 2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
          3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102],
        [ 4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
          5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735],
        [ 6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
          7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367],
        [ 8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
          9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ]]),
 array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
         1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
         2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
         3.06122449,  3.26530612, 

In [107]:
array_15.size

50

In [108]:
array_15.dtype

dtype('float64')